#!/usr/bin/env python3
"""Render the human-facing pages from data/.

`aggregate.py` collects pointers. This turns them into pages a person who is not
a programmer can act on:

    docs/VIEWERS.md    — read the documents in a browser, nothing to install
    docs/DOWNLOADS.md  — get the actual files, easiest route first, per release

Run it after aggregate.py:

    python scripts/render_docs.py

Stdlib only, no network. Both pages are generated — edit this script, not them.
"""
from __future__ import annotations

import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "data")
DOCS = os.path.join(ROOT, "docs")

GENERATED = "<!-- Generated by scripts/render_docs.py — edit the script, not this file. -->"


def load(name, default):
    try:
        with open(os.path.join(DATA, name), encoding="utf-8") as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return default


def natural_key(s: str):
    return [int(p) if p.isdigit() else p.lower() for p in re.split(r"(\d+)", s or "")]


def parse_size(label):
    """'1.23 GB' -> bytes, for ordering smallest-first. Unknown sorts last."""
    if not label:
        return float("inf")
    m = re.search(r"([\d.]+)\s*(TB|GB|MB|KB|B)", label, re.I)
    if not m:
        return float("inf")
    mult = {"b": 1, "kb": 1 << 10, "mb": 1 << 20, "gb": 1 << 30, "tb": 1 << 40}
    return float(m.group(1)) * mult[m.group(2).lower()]


def health_map():
    h = load("health.json", {})
    return {r["url"]: r for r in h.get("results", [])}, h.get("checked")


# ---- viewers ---------------------------------------------------------------
def render_viewers():
    viewers = load("viewers.json", [])
    health, checked = health_map()

    hosted = [v for v in viewers if not v.get("needs_download")]
    local = [v for v in viewers if v.get("needs_download")]

    L = [
        "# Read the documents in your browser",
        "",
        GENERATED,
        "",
        "**You do not need to download anything to read these files.** Other people have",
        "already put the documents online in a form you can search and read like any",
        "website. Start here. Downloading the raw releases only makes sense if you need the",
        "original files — see [DOWNLOADS.md](DOWNLOADS.md) for that.",
        "",
        "None of these sites are run by this project. They are listed because they work and",
        "are publicly available, not because their contents have been checked for accuracy.",
        "",
    ]

    if checked:
        L += [f"Reachability last checked **{checked}**.", ""]

    L += [
        "## Open in a browser — nothing to install",
        "",
    ]

    for v in hosted:
        st = health.get(v["url"], {})
        badge = ""
        if st:
            if st.get("verdict") == "ok":
                badge = " ✅"
            elif st.get("verdict") == "blocked":
                badge = " ⚠️ *(refuses automated checks; usually fine in a browser)*"
            else:
                badge = f" ❌ *(last check: {st.get('verdict')})*"

        L += [f"### [{v['name']}]({v['url']}){badge}", ""]
        L += [v["summary"], ""]
        meta = [f"Run by {v['operator']}"]
        if not v.get("needs_account"):
            meta.append("no account needed")
        L += ["*" + " · ".join(meta) + "*", ""]
        if v.get("note"):
            L += [f"> {v['note']}", ""]
        if v.get("caution"):
            L += [f"> ⚠️ **Caution.** {v['caution']}", ""]
        if v.get("source_repo"):
            L += [f"Source code: {v['source_repo']}", ""]

    if local:
        L += [
            "## For researchers — run it yourself",
            "",
            "These are projects you install and run on your own machine. More capable, but",
            "they assume you are comfortable with a terminal.",
            "",
            "| Project | What it does |",
            "|---------|--------------|",
        ]
        for v in local:
            L.append(f"| [{v['name']}]({v['url']}) | {v['summary']} |")
        L.append("")

    L += [
        "## A word before you start",
        "",
        "These documents describe the sexual abuse of children. They contain names,",
        "photographs and contact details of victims, and the redactions applied before",
        "release were not applied consistently.",
        "",
        "**Being named in these files is not evidence of wrongdoing.** The releases include",
        "witnesses, investigators, household staff, hotel bookings and unrelated",
        "correspondence. People have already been misidentified online on the strength of a",
        "single filename.",
        "",
        "If you find something that appears to identify a victim, do not republish it.",
        "",
    ]
    return "\n".join(L)


# ---- downloads -------------------------------------------------------------
def render_downloads():
    datasets = sorted(load("datasets.json", []), key=lambda d: parse_size(d.get("size_label")))
    health, checked = health_map()

    L = [
        "# Getting the actual files",
        "",
        GENERATED,
        "",
        "Only do this if you need the original documents. To *read* them, the browser",
        "viewers in [VIEWERS.md](VIEWERS.md) are easier and need nothing installed.",
        "",
        "Releases are listed **smallest first**. Data Set 5 is 61 MB and downloads in under a",
        "minute; Data Set 9 is roughly 180 GB and is not something you start by accident.",
        "",
    ]
    if checked:
        L += [f"Link reachability last checked **{checked}**.", ""]

    L += [
        "## Three ways to download, easiest first",
        "",
        "**1. Click a link in your browser.** Where a release has an `archive.org` or",
        "`justice.gov` file link below, clicking it downloads the ZIP like any other file.",
        "Nothing to install. This is the right choice for the smaller releases.",
        "",
        "**2. Use a download manager** for the multi-gigabyte ones, so an interrupted",
        "transfer resumes instead of starting over. Any browser extension or tool that",
        "supports resuming will do.",
        "",
        "**3. Use BitTorrent** for the largest releases, and to help keep them available.",
        "A *magnet link* is a line of text starting with `magnet:?` that tells a torrent",
        "program what to fetch. To use one: install a torrent client",
        "([qBittorrent](https://www.qbittorrent.org/) is free and open source), copy the",
        "magnet text below, and use **File → Add torrent link** (or paste it into the",
        "address bar). Each code block here has a copy button on its right-hand side.",
        "",
        "Torrents are also how this material stays online: while your client is open, you",
        "are serving the files to other people. That is the point.",
        "",
        "## Checking you got the real thing",
        "",
        "Some releases publish a **SHA-256** — a fingerprint of the file. If yours matches,",
        "you have a byte-identical copy of what the publisher put out. To check it:",
        "",
        "```bash",
        "# macOS / Linux",
        "shasum -a 256 'DataSet 5.zip'",
        "",
        "# Windows PowerShell",
        "Get-FileHash 'DataSet 5.zip' -Algorithm SHA256",
        "```",
        "",
        "Or let the included tool identify any file you already downloaded:",
        "",
        "```bash",
        "python scripts/verify.py check 'DataSet 5.zip'",
        "```",
        "",
        "A mismatch is not proof of tampering — mirrors legitimately repackage these",
        "archives. It means *this is not the exact file that checksum describes*.",
        "",
        "---",
        "",
    ]

    for d in datasets:
        name, size = d["dataset"], d.get("size_label") or "size unknown"
        L += [f"## {name} — {size}", ""]
        if not d.get("complete", True):
            L += [
                "> ⚠️ **Incomplete at the source.** Files were removed from the government",
                "> site after publication. Community reconstructions cover more of this",
                "> release than the official ZIP does. Do not treat any single copy here as",
                "> the complete record.",
                "",
            ]

        browser = [a for a in d["artifacts"] if a["kind"].startswith(("official", "mirror"))]
        torrents = [a for a in d["artifacts"] if a["kind"] == "torrent"]

        alive = [a for a in browser if health.get(a["url"], {}).get("verdict") == "ok"]
        if alive:
            L += ["**Download in your browser:**", ""]
            for a in alive:
                where = "official government site" if a["kind"] == "official" else a["kind"].split(":", 1)[-1]
                L.append(f"- [{where}]({a['url']})")
            L.append("")

        dead = [a for a in browser if a not in alive]
        if dead:
            L += ["<details><summary>Links that did not respond at the last check</summary>", ""]
            for a in dead:
                st = health.get(a["url"], {})
                why = st.get("verdict", "unchecked")
                hint = " — the host refused our check; may still work in a browser" if why == "blocked" else ""
                L.append(f"- `{a['url']}` — {why}{hint}")
            L += ["", "</details>", ""]

        if torrents:
            L += ["**Or by torrent** — copy this into your torrent client:", ""]
            for a in torrents:
                L += ["```text", a["url"], "```", ""]

        shas = [(a, a["sha256"]) for a in d["artifacts"] if a.get("sha256")]
        if shas:
            L += ["<details><summary>Published SHA-256 checksums</summary>", ""]
            for a, s in shas:
                L += [f"`{a['kind']}`", "", "```text", s, "```", ""]
            L += ["</details>", ""]

        L.append("")

    L += [
        "## After you download",
        "",
        "The ZIPs expand into folders of scanned PDFs and native files, named by their",
        "production number (`EFTA…`, `DOJ-OGR-…`) rather than by subject. There is no index",
        "inside. If you are looking for something specific rather than preserving the whole",
        "set, the browser viewers in [VIEWERS.md](VIEWERS.md) or the searchable text corpora",
        "in [`data/derivatives.json`](../data/derivatives.json) will get you there faster.",
        "",
    ]
    return "\n".join(L)


def render_library():
    lib = load("official_library.json", {})
    if not lib:
        return None
    health, _ = health_map()

    L = [
        "# What the government actually published",
        "",
        GENERATED,
        "",
        "A snapshot of the **DOJ Epstein Library** as it is laid out on justice.gov — not",
        "just the bulk ZIP releases everyone mirrors, but the individually published court",
        "records, FOIA productions and letters to Congress that are easy to miss.",
        "",
        "The Department has reorganized this page before and has removed files after",
        "publication. This snapshot records what was published and where, so a later",
        "reshuffle does not erase the fact that something existed.",
        "",
        f"Source: <{lib.get('source')}> · captured **{lib.get('fetched')}**"
        + (f" · library last updated **{lib['site_last_updated']}**" if lib.get("site_last_updated") else ""),
        "",
        f"**{lib.get('total_entries', 0)} entries across {len(lib.get('sections', []))} sections.**",
        "",
        "> The DOJ applies redactions to protect victim identities, and asks that anything",
        "> improperly disclosed be reported to **EFTA@usdoj.gov**. In audio files, victim",
        "> names are redacted with a steady tone rather than removed.",
        "",
    ]

    for sec in lib.get("sections", []):
        L += [f"## {sec['title']}", "", f"{len(sec['entries'])} entries.", ""]
        L += ["| Entry | Status |", "|-------|--------|"]
        for e in sec["entries"]:
            st = health.get(e["url"], {}).get("verdict")
            mark = {"ok": "✅", "gone": "❌ gone", "blocked": "⚠️ refused check"}.get(st, "—")
            name = e["name"].replace("|", r"\|")
            L.append(f"| [{name}]({e['url']}) | {mark} |")
        L.append("")

    L += [
        "## Why this matters",
        "",
        "Most mirrors and torrents cover the twelve EFTA Data Sets and nothing else. The",
        "court records, FOIA productions and prior disclosures listed above are published",
        "separately, are not in those bulk archives, and disappear from view whenever the",
        "page is restructured. If you are researching a specific case rather than the bulk",
        "corpus, this is where to look.",
        "",
    ]
    return "\n".join(L)


def main():
    os.makedirs(DOCS, exist_ok=True)
    pages = [("VIEWERS.md", render_viewers()), ("DOWNLOADS.md", render_downloads())]
    lib = render_library()
    if lib:
        pages.append(("OFFICIAL-LIBRARY.md", lib))
    for fname, body in pages:
        path = os.path.join(DOCS, fname)
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(body.rstrip() + "\n")
        print(f"wrote docs/{fname} ({os.path.getsize(path):,} bytes)")


if __name__ == "__main__":
    main()
